name: AOpenWrt-xm-im


on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      branch:
        description: '选择仓库的分支：'
        default: 'master'
        required: true
        type: choice
        options: [ master, stable, openwrt-21.02, openwrt-23.05 ]
      config_s:
        description: '配置文件'
        default: 'Vip-Mini'
        required: true
        type: choice
        options: [ Vip-Mini,Free-Mini, Free-Plus,  Vip-Plus,"NO" ]
      cpu_s:
        description: 'CPU优选'
        required: true
        default: '8'
        type: choice
        options:
          - '8'
          - '8370C'
          - '8272CL'
          - '8171M'
      target:
        description: '选择要生成的机型：'
        default: 'r2s'
        required: true
        type: choice
        options: [  rm2100, xm2100 ]
      date_s:
        description: '固件日期'
        default: 'default'
        required: false
env:
  # branch REPO_URL: https://github.com/DHDAXCW/lede-rockchip
  #REPO_BRANCH: openwrt-21.02
  FEEDS_CONF: feeds.conf.default
  DIY_P1_SH: diy/diyr.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: false
  UPLOAD_WETRANSFER: false
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    name: lede-${{github.event.inputs.config_s}}-${{github.event.inputs.target}}-${{github.event.inputs.branch}}-${{github.event.inputs.date_s}}
    env:
      CONFIG_S: ${{github.event.inputs.config_s}}
      CPU_S: ${{github.event.inputs.cpu_s}}
      DATE_S: ${{github.event.inputs.date_s}}
      TARGET_DEVICE: ${{github.event.inputs.target}}
      REPO_BRANCH: ${{github.event.inputs.branch}}
    steps:
      - name: Checkout
        uses: actions/checkout@main
      
      - name: Check server performance
        run: |
         echo "警告⚠"
         echo "若分配的服务器性能不足，务必及时取消，重新运行！"
         echo "已知编译成功CPU型号：8370C,8171M"
         echo "已知性能不足CPU型号：8272CL E5-2673"
         echo -e "-------------- ------------CPU信息------------------------------------------\n"
         echo "CPU物理数量:$(cat /proc/cpuinfo| grep "physical id"| sort| uniq| wc -l)"
         echo -e "CPU核心及版本信息：$(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c) \n"
         echo "-------------------------------内存信息-------------------------------------------"
         echo "已安装内存详细信息："
         sudo lshw -short -C memory | grep GiB
         echo -e "\n"
         echo "-----------------------------硬盘信息---------------------------------------------"
         echo -e  "硬盘数量：$(ls /dev/sd* | grep -v [1-9] | wc -l) \n"
         echo "硬盘详情："
         df -Th
         
         if grep  $CPU_S "/proc/cpuinfo" ; then
          echo "CPU YES！！！"
          echo "CKCPU=success" >> $GITHUB_ENV
         else
             echo "CPU NO！！！"
             echo "CKCPU=failure" >> $GITHUB_ENV
             exit 1
         fi
      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi $(docker images -q)
          sudo -E rm -rf $(cat $GITHUB_WORKSPACE/Depends.txt | sed -n "1{s/\r$//;p;q}")
          sudo -E apt -yqq update
          sudo -E apt -yqq purge $(cat $GITHUB_WORKSPACE/Depends.txt | sed -n "2{s/\r$//;p;q}")
          sudo -E apt -yqq full-upgrade
          sudo -E apt -yqq install $(cat $GITHUB_WORKSPACE/Depends.txt | sed -n "3{s/\r$//;p;q}")
          sudo -E apt -yqq autoremove --purge
          sudo -E apt -yqq autoclean
          sudo -E apt -yqq clean
          sudo -E systemctl daemon-reload
          sudo timedatectl set-timezone "Asia/Shanghai"
          sudo mkdir -p /mnt/workdir
          sudo chown $USER:$GROUPS /mnt/workdir
      - name: Clone source code
        working-directory: /mnt/workdir
        run: |
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
          ln -sf /mnt/workdir/openwrt $GITHUB_WORKSPACE/openwrt
          if [[ $DATE_S == 'default' ]]; then
          echo "DATA=`date +%Y%m%d_%H -d +"12"hour`" >> $GITHUB_ENV
          else 
          echo "DATA=$DATE_S" >>$GITHUB_ENV
          fi
          cd openwrt
          rm -rf ./tmp && rm -rf .config
      - name: Update feeds
        run: |
          mv -f ./.github/tmp/* ./
          cd openwrt 
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: Update package
        run: |
         # [ -e $CONFIG_FILE ] && mv $CONFIG_FILE ./openwrt/.config
         #[ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
         chmod +x ${DIY_P1_SH}
         cd openwrt
         $GITHUB_WORKSPACE/$DIY_P1_SH
         chmod -R 755 .
      - name: Generate configuration file
        run: |
          cd openwrt
          cat  $GITHUB_WORKSPACE/config/${TARGET_DEVICE}  > .config
          case "${CONFIG_S}" in
          Vip*)        
          cat  $GITHUB_WORKSPACE/config/Vip  >> .config
          ;;
          Free*)
          cat  $GITHUB_WORKSPACE/config/Free  >> .config
          ;;
          esac
          echo -e 'CONFIG_DEVEL=y\nCONFIG_CCACHE=y' >> .config #Cache.Speedup
          make defconfig 
      - name: Make download
        run: |
          cd openwrt
          make download -j32
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;
          df -h
      - name: Compile Packages
        id: compile
        run: |

         cd openwrt 
         #mkdir -p files/etc/uci-defaults/
         #cp $GITHUB_WORKSPACE/scriptx/init-settings.sh files/etc/uci-defaults/99-init-settings
         make -j$(($(nproc)+1)) || make -j1 V=s

      - name: Upload Firmware
        uses: actions/upload-artifact@main
        with:
          name: ${{ env.DATA }}-SirpdboyOpenWrt-bin-Firmware
          path: ./openwrt/bin
      - name: Prepare Artifact
        run: |
          mkdir -p ./rm2100
          find ./openwrt/bin/ -name "*2100-squashfs*.bin" | xargs -i mv -f {} ./rm2100
          
          cd ./rm2100
          rm -rf *rootfs0.bin *kernel1.bin *kernel.bin  
          gzip *.bin || true
          echo -e "Sirpdboy-RM2100-${{ env.DATA }}\n" > 版本日期和MD5信息.txt
          echo -e "【固件插件说明与各版本下载链接】：https://github.com/sirpdboy/openwrt/ \n"  >> 版本日期和MD5信息.txt
          echo -e "MD5: \n" >> 版本日期和MD5信息.txt
          md5sum *2100* >> 版本日期和MD5信息.txt || true
          ls

      - name: Upload Firmware
        uses: actions/upload-artifact@main
        with:
          name: ${{ env.DATA }}-SirpdboyOpenWrt-IPV6-RM2100-Firmware
          path: ./rm2100
