#
# Copyright (c) 2019-2021 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# File: .github/workflows/update-checker.yml
# Description: Source code update checker
#

name: -Clear Checker-

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 ? * FRI  
jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Cancel Running Wrkflows
      uses: styfle/cancel-workflow-action@main
      if: github.event.inputs.cancel=='1'
      with:
        ignore_sha: true
        workflow_id: ${{secrets.WORK_ID}}
        access_token: ${{github.token}}

    - name: Delete Workflow Runs
      uses: loso3000/delete-workflow-runs@main
      with:
        retain_min: 0
        keep_minimum_runs: 0

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
          token: ${{ secrets.AUTH_PAT }}
          repository: ${{ github.repository }}
          retain_days: 1
          
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 2
        keep_minimum_runs: 3
