name: Openwrt-n1-lean-db

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: script/dzn1
  DIY_P1_SH: script/aipv6mini.sh
jobs:
  build_openwrt:
    name: OpenWrt_Build 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |

          docker rmi `docker images -q`
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /usr/lib/jvm /opt/ghc /swapfile
          sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
          sudo -E apt-mark hold grub-efi-amd64-signed
          sudo -E apt update
          sudo -E apt -y purge azure-cli* docker* ghc* zulu* llvm* firefox google* dotnet* powershell* openjdk* mysql* php* mongodb* dotnet* moby* snap*
          sudo -E apt -y full-upgrade
          sudo -E apt -y install ack antlr3 aria2 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
          sudo -E systemctl daemon-reload
          sudo -E apt -y autoremove --purge
          sudo -E apt clean
          sudo -E timedatectl set-timezone "Asia/Shanghai"
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
      - name: download
        run: |
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
          cd openwrt
          git clone https://github.com/sirpdboy/sirpdboy-package ./package/diy
          rm -rf ./tmp && rm -rf .config
      - name: Update feeds
        run: |
          cd openwrt 
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: Update package
        run: |
         [ -e $CONFIG_FILE ] && mv $CONFIG_FILE ./openwrt/.config
         chmod +x ./$DIY_P1_SH
         cd openwrt
         ../$DIY_P1_SH
         chmod -R 755 .
      - name: Generate configuration file
        run: |
          cd openwrt
          make defconfig 
      - name: Make download
        run: |
          cd openwrt
          make download -j8
      - name: Compile firmware
        id: compileopenwrt
        continue-on-error: true
        run: |
         df -h
         cd openwrt
         make -j$(($(nproc) + 1)) || make -j$(($(nproc) + 1)) V=s
         echo $?
      - name: If Error
        if: steps.compileopenwrt.outcome == 'failure'
        run: |
          cat openwrt/.config
          echo '================================================================'
          cd openwrt && make -j1 V=s
          echo $?
      - name: Upload Firmware
        uses: actions/upload-artifact@main
        with:
          name: n1-OpenWrt-IPV6-Firmware-bin
          path: ./openwrt/bin
      - name: Package Armvirt as OpenWrt
        uses: ophub/flippy-openwrt-actions@main
        env:
           OPENWRT_ARMVIRT: openwrt/bin/targets/*/*/*.tar.gz
           PACKAGE_SOC: s905d
           KERNEL_VERSION_NAME: 5.10.103
      - name: Upload OpenWrt Firmware to Release
        uses: ncipollo/release-action@v1
        with:
         tag: openwrt_armvirt_${{ env.PACKAGED_OUTPUTDATE }}
         artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
         allowUpdates: true
         token: ${{ secrets.GITHUB_TOKEN }}
         body: |
          This is OpenWrt firmware for Armvirt 64
          * Firmware information
          Default IP: 192.168.2.1
          Default username: root
          Default password: tiktok
          Default WIFI name: Tiktok
          Default WIFI password: 123456
          Install to EMMC: Login to OpenWrt → System → Amlogic Service → Install OpenWrt
