
name: OpenWrt_gl_sft1200_mulder125


on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
#  schedule:
#    - cron: 0 21 */7 * * 

env:
  REPO_URL: https://github.com/mulder125/Openwrt-SFT1200
  REPO_BRANCH: main
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config.sft1200
  DIY_P1_SH: ipv4.sh
  DIY_P2_SH: uppackage.sh

jobs:

  build_openwrt:

    name: OpenWrt_Build 

    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* android*
          sudo -E apt-get update
          sudo apt-get install -y expect ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib g++-multilib git git-core gperf haveged help2man intltool lib32gcc1 libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncurses5-dev libreadline-dev libssl-dev libtool libz-dev lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip python3-ply python-docutils qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          sudo timedatectl set-timezone "Asia/Shanghai"
      - name: Update feeds
        run: |
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
          cd openwrt
          ./scripts/feeds update -a && ./scripts/feeds install -a
      - name: Update package
        run: |
         # [ -e $CONFIG_FILE ] && mv ./openwrt/$CONFIG_FILE ./openwrt/.config
         # chmod +x ./$DIY_P1_SH
         # chmod +x ./$DIY_P2_SH
         cd openwrt
         
         # ../$DIY_P1_SH
         # ../$DIY_P2_SH
         chmod -R 755 .
      
      - name: Generate configuration file
        working-directory: ./openwrt
        run: |
          load $CONFIG_FILE
      - name: Make download
        working-directory: ./openwrt
        run: |
          make download -j8
          find dl -size -1024c -exec rm -f {} \;
      - name: Compile firmware
        working-directory: ./openwrt
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin

      - name: Prepare Artifact
        run: |
          mkdir -p ./new1/firmware
          mkdir -p ./new1/package
          cp -rf $(find ./openwrt/bin/packages/ -type f -name "*.ipk") ./new1/package
          find ./openwrt/bin/targets/ -name "*combined*img*" | xargs -i mv -f {} ./new1/firmware
          cd ./new1/firmware
          gzip *.img | true
          # echo "${{ env.DATA}}" > version.txt
          # md5=$((md5sum *squashfs-sysupgrade* || md5sum *squashfs-combined-efi*) | awk '{print $1}') 2>/dev/null
          # echo $md5 >> version.txt
      - name: Upload Firmware
        uses: actions/upload-artifact@main
        with:
          name: SirpdboyOpenWrt-sf1200-Firmware
          path: ./new1/firmware
      - name: Upload  IPK
        uses: actions/upload-artifact@main
        with:
          name: SirpdboyOpenWrt-sf1200-Ipk
          path: ./new1/package

      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 14
          keep_minimum_runs: 3
